server:
  port: 8443
  # servlet:
  #   context-path: /api
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: keystore.p12
    key-store-password: changeit
    key-alias: demo

spring:
  application:
    name: personal-finance-apis
  profiles:
    default: local
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: "/h2-console"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      profiles: ${spring.profiles.active}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org:
      springframework:
        security: trace
